version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing Dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - zip lambda_function *

artifacts:
  files:
    - lambda_function.zip
